-- Alter Table Script
ALTER TABLE Office
  ADD CONSTRAINTS office_manager_FK FOREIGN KEY (employee_ID) REFERENCES Employee(employee_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Employee
  ADD CONSTRAINTS office_assigned_FK FOREIGN KEY (office_ID) REFERENCES Office(Office_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE taxi
  ADD CONSTRAINTS taxi_assigned_FK FOREIGN KEY (employee_ID) REFERENCES Employee(employee_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Business_Client
  ADD CONSTRAINTS Business_Client_contract_ID_FK FOREIGN KEY (contract_ID) REFERENCES Contract(contract_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Contract
  ADD CONSTRAINTS Contract_office_ID_FK FOREIGN KEY (office_ID) REFERENCES Office(office_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
  ADD CONSTRAINTS Job_employee_ID_FK FOREIGN KEY (employee_ID) REFERENCES Employee(employee_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
  ADD CONSTRAINTS Job_contract_ID_FK FOREIGN KEY (contract_ID) REFERENCES Contract(contract_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
  ADD CONSTRAINTS Job_client_ID_FK FOREIGN KEY (private_client_ID) REFERENCES Private_Client(private_client_ID) 
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
  ADD CONSTRAINTS Job_job_ID_FK FOREIGN KEY (job_ID) REFERENCES Job(job_ID)
  ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

